bfsapp/urls.py
from django.conf.urls import url 
from .views import *


urlpatterns = [
    url(r'^school-admin/logout/$', AdminLogout.as_view(),
        name='adminlogout'),
    url(r'^school-admin/login/$', AdminLogin.as_view(),
        name='adminlogin'),
    url(r'^school-admin/$', AdminHomeView.as_view(), name='adminhome'),



    url(r'^school-admin/videos/$',
        AdminVideoListView.as_view(), name='adminvideolist'),
    url(r'^school-admin/videos/create/$',
        AdminVideoCreateView.as_view(), name='adminvideocreate'),
    url(r'^school-admin/videos/(?P<pk>\d+)/update/$',
        AdminVideoUpdateView.as_view(), name='adminvideoupdate'),
    url(r'^school-admin/videos/(?P<pk>\d+)/delete/$',
        AdminVideoDeleteView.as_view(), name='adminvideodelete'),



    url(r'^school-admin/blogs/$',
        AdminBlogListView.as_view(), name='adminbloglist'),
    url(r'^school-admin/blogs/create/$',
        AdminBlogCreateView.as_view(), name='adminblogcreate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/update/$',
        AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/delete/$',
        AdminBlogDeleteView.as_view(), name='adminblogdelete'),

    url(r'^school-admin/events/$',
        AdminEventListView.as_view(), name='admineventlist'),
    url(r'^school-admin/events/create/$',
        AdminEventCreateView.as_view(), name='admineventcreate'),
    url(r'^school-admin/events/(?P<pk>\d+)/update/$',
        AdminEventUpdateView.as_view(), name='admineventupdate'),
    url(r'^school-admin/events/(?P<pk>\d+)/delete/$',
        AdminEventDeleteView.as_view(), name='admineventdelete'),

    url(r'^school-admin/gallery/$',
        AdminGalleryListView.as_view(), name='admingallerylist'),
    url(r'^school-admin/gallery/create/$',
        AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/update/$',
        AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/delete/$',
        AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    url(r'^school-admin/notices/$',
        AdminNoticeListView.as_view(), name='adminnoticelist'),
    url(r'^school-admin/notices/create/$',
        AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/update/$',
        AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/delete/$',
        AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    url(r'^school-admin/staffs/$',
        AdminStaffListView.as_view(), name='adminstafflist'),
    url(r'^school-admin/staffs/create/$',
        AdminStaffCreateView.as_view(), name='adminstaffcreate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/update/$',
        AdminStaffUpdateView.as_view(), name='adminstaffupdate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/delete/$',
        AdminStaffDeleteView.as_view(), name='adminstaffdelete'),

    url(r'^school-admin/testimonials/$',
        AdminTestimonialListView.as_view(), name='admintestimoniallist'),
    url(r'^school-admin/testimonials/create/$',
        AdminTestimonialCreateView.as_view(), name='admintestimonialcreate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/update/$',
        AdminTestimonialUpdateView.as_view(), name='admintestimonialupdate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/delete/$',
        AdminTestimonialDeleteView.as_view(), name='admintestimonialdelete'),


    url(r'^school-admin/activities/$',
        AdminActivitiesListView.as_view(), name='adminactivitieslist'),
    url(r'^school-admin/activities/create/$',
        AdminActivitiesCreateView.as_view(), name='adminactivitiescreate'),
    url(r'^school-admin/activities/(?P<pk>\d+)/update/$',
        AdminActivitiesUpdateView.as_view(), name='adminactivitiesupdate'),
    url(r'^school-admin/activities/(?P<pk>\d+)/delete/$',
        AdminActivitiesDeleteView.as_view(), name='adminactivitiesdelete'),



    url(r'^school-admin/features/$',
        AdminFeaturesListView.as_view(), name='adminfeatureslist'),
    url(r'^school-admin/features/create/$',
        AdminFeaturesCreateView.as_view(), name='adminfeaturescreate'),
    url(r'^school-admin/features/(?P<pk>\d+)/update/$',
        AdminFeaturesUpdateView.as_view(), name='adminfeaturesupdate'),
    url(r'^school-admin/features/(?P<pk>\d+)/delete/$',
        AdminFeaturesDeleteView.as_view(), name='adminfeaturesdelete'),




    url(r'^school-admin/services/$',
        AdminServicesListView.as_view(), name='adminserviceslist'),
    url(r'^school-admin/services/create/$',
        AdminServicesCreateView.as_view(), name='adminservicescreate'),
    url(r'^school-admin/services/(?P<pk>\d+)/update/$',
        AdminServicesUpdateView.as_view(), name='adminservicesupdate'),
    url(r'^school-admin/services/(?P<pk>\d+)/delete/$',
        AdminServicesDeleteView.as_view(), name='adminservicesdelete'),



    url(r'^school-admin/download/$',
        AdminDownloadListView.as_view(), name='admindownloadlist'),
    url(r'^school-admin/download/create/$',
        AdminDownloadCreateView.as_view(), name='admindownloadcreate'),
    url(r'^school-admin/download/(?P<pk>\d+)/update/$',
        AdminDownloadUpdateView.as_view(), name='admindownloadupdate'),
    url(r'^school-admin/download/(?P<pk>\d+)/delete/$',
        AdminDownloadDeleteView.as_view(), name='admindownloaddelete'),



    url(r'^school-admin/routine/$',
        AdminRoutineListView.as_view(), name='adminroutinelist'),
    url(r'^school-admin/routine/create/$',
        AdminRoutineCreateView.as_view(), name='adminroutinecreate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/update/$',
        AdminRoutineUpdateView.as_view(), name='adminroutineupdate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/delete/$',
        AdminRoutineDeleteView.as_view(), name='adminroutinedelete'),




    url(r'^school-admin/result/$',
        AdminResultListView.as_view(), name='adminresultlist'),
    url(r'^school-admin/result/create/$',
        AdminResultCreateView.as_view(), name='adminresultcreate'),
    url(r'^school-admin/result/(?P<pk>\d+)/update/$',
        AdminResultUpdateView.as_view(), name='adminresultupdate'),
    url(r'^school-admin/result/(?P<pk>\d+)/delete/$',
        AdminResultDeleteView.as_view(), name='adminresultdelete'),



    url(r'^school-admin/slider/$',
        AdminSliderListView.as_view(), name='adminsliderlist'),
    url(r'^school-admin/slider/create/$',
        AdminSliderCreateView.as_view(), name='adminslidercreate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/update/$',
        AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/delete/$',
        AdminSliderDeleteView.as_view(), name='adminsliderdelete'), 



    url(r'^school-admin/vacancii/$',
        AdminVacanciiListView.as_view(), name='adminvacanciilist'),
    url(r'^school-admin/vacancii/create/$',
        AdminVacanciiCreateView.as_view(), name='adminvacanciicreate'),
    url(r'^school-admin/vacancii/(?P<pk>\d+)/update/$',
        AdminVacanciiUpdateView.as_view(), name='adminvacanciiupdate'),
    url(r'^school-admin/vacancii/(?P<pk>\d+)/delete/$',
        AdminVacanciiDeleteView.as_view(), name='adminvacanciidelete'),



    url(r'^school-admin/price/$',
        AdminPriceListView.as_view(), name='adminpricelist'),
    url(r'^school-admin/price/create/$',
        AdminPriceCreateView.as_view(), name='adminpricecreate'),
    url(r'^school-admin/price/(?P<pk>\d+)/update/$',
        AdminPriceUpdateView.as_view(), name='adminpriceupdate'),
    url(r'^school-admin/price/(?P<pk>\d+)/delete/$',
        AdminPriceDeleteView.as_view(), name='adminpricedelete'),
  




    url(r'^school-admin/messages/$',
        AdminMessageListView.as_view(), name='adminmessagelist'),
    url(r'^school-admin/messages/(?P<pk>\d+)/$',
        AdminMessageDetailView.as_view(), name='adminmessagedetail'),
    url(r'^school-admin/messages/(?P<pk>\d+)/delete/$',
        AdminMessageDeleteView.as_view(), name='adminmessagedelete'),



    url(r'^school-admin/admission/$',
        AdminAdmissionListView.as_view(), name='adminadmissionlist'),
    url(r'^school-admin/admission/(?P<pk>\d+)/$',
        AdminAdmissionDetailView.as_view(), name='adminadmissiondetail'),
    url(r'^school-admin/admission/(?P<pk>\d+)/delete/$',
        AdminAdmissionDeleteView.as_view(), name='adminadmissiondelete'),


    url(r'^school-admin/vacancy/$',
        AdminVacancyListView.as_view(), name='adminvacancylist'),
    url(r'^school-admin/vacancy/(?P<pk>\d+)/$',
        AdminVacancyDetailView.as_view(), name='adminvacancydetail'),
    url(r'^school-admin/vacancy/(?P<pk>\d+)/delete/$',
        AdminVacancyDeleteView.as_view(), name='adminvacancydelete'),

     







    # client side


    url(r'^$', ClientHomeView.as_view(), name='clienthome'),
	url(r'^home$', HomeView.as_view(), name='home'),
	url(r'^about/$', ClientAboutView.as_view(), name='clientabout'),
    url(r'^service/$', ClientServiceListView.as_view(), name='clientservicelist'),
	url(r'^gallery/$', ClientGalleryListView.as_view(), name='clientgallerylist'),
	url(r'^blog/$', ClientBlogListView.as_view(), name='clientbloglist'),
    url(r'^blogs/(?P<pk>\d+)/$', ClientBlogDetailView.as_view(), name='clientblogdetail'),
	url(r'^activities/$', ClientActivitiesListView.as_view(), name='clientactivitieslist'),
    url(r'^activiti/(?P<pk>\d+)/$', ClientActivitiesDetailView.as_view(), name='clientactivitiesdetail'),
    url(r'^contact/$', ClientContactView.as_view(), name='clientcontact'),
    url(r'^events/(?P<pk>\d+)/$', ClientEventDetailView.as_view(), name='clienteventdetail'),
    url(r'^admission/$', ClientAdmissionView.as_view(), name='clientadmission'),
    url(r'^admissionn/$', ClientAdmissionnView.as_view(), name='clientadmissionn'),

bfsproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('bfsapp.urls', namespace='bfsapp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bfsapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()





class Blog(TimeStamp):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to='blog/')
    content = models.TextField()
    author = models.CharField(max_length=200)

    def __str__(self):
        return self.title



class Video(TimeStamp):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=255)


    def __str__(self):
        return self.title



class Event(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='event/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title




class Notice(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title


class Staff(TimeStamp):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='staff/')
    post = models.CharField(max_length=100)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name



class Features(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='feature/')

    def __str__(self):
        return self.title



class Gallery(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


class Slider(TimeStamp):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=255)

    def __str__(self):
        return self.image.url


class Activities(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='activities/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title


class Testimonial(TimeStamp):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=50)
    says = models.TextField()

    def __str__(self):
        return self.name


class Service(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='service/', null=True, blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title



class Download(TimeStamp):
    title = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')
    content = models.TextField()
    image = models.ImageField(upload_to='service/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title


class Message(TimeStamp):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name



class Result(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Routine(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Admission(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    grade = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Vacancy(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Qualification = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    subject = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name




class Vacancii(TimeStamp):
    title = models.TextField()
    content = models.TextField()


    def __str__(self):
        return self.title



class Price(TimeStamp):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

class A1(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A2(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A3(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A4(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A5(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A6(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A7(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A8(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


    

templates/bfsapp/clienttemplates/ClientdownloadList.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}


{% block content %}
<br><br>
<div class="container">
	<div class="row">
		{% for download in downloads %}
		<div class="col-md-3">
			<div>
				<a href="{{download.document.url}}"  target="_blank"><img src="{{download.image.url}}" class="img-responsive img-thumbnail"></a>
			</div>
			<div>
				<h4>{{download.title}}</h4>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

templates/bfsapp/clienttemplates/Clientresultlist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}

{% block content %}
<br><br>

<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>
  <div class="container">
    <div class="student-grids">
      <div class="col-md-8 student-grid">
<center><h3 style="color: green"> Exam Result</h3></center><br>
<table id="customers">
  <tr>
    <th><h3>Class</h3></th>
    <th><h3>Download</h3></th>
     </tr>
  {% for result in results %}  
 
  <tr>
    <td>{{result.grade}}</td>
    <td><a href="{{result.document.url}}" download="">{{result.document}}</a></td>
  {% endfor %}
  </tr>
  
</table><br><br>
</div>
</div>
</div>



{% endblock content %}

templates/bfsapp/clienttemplates/clientbloglist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block blog %}active{% endblock blog %}


{% block content %}

<div class="banner-w3agile">
			<div class="container">
				<h3><a href="">Blog</a></h3>
			</div>
		</div>

		<!--content-->
		<div class="content">
			<div class="courses-w3ls">
				<div class="container">
					<h2 class="tittle">Blogs</h2>
					{% for blog in blogs %}
					<div class="course-grids">
						<div class="col-md-3 course-grid">
							<div class="mask">
								<img src="{{blog.image.url}}" class="img-responsive zoom-img" />
							</div>
						</div>
						<div class="col-md-9 course-grid1 gri">
							<h4>{{blog.title}}</h4>
							<p>{{blog.content|truncatewords:'50'}}
                               <a class="btn btn-primary" href="{% url 'bfsapp:clientblogdetail' blog.id %}">Read More</a>
							</p>
							<p>Author:{{blog.author}}</p>
						
						</div>
						<div class="clearfix"></div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>	


{% endblock content %}

templates/bfsapp/clienttemplates/clientgallerylist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block gallery %}active{% endblock gallery %}


{% block content %}

<div class="banner-w3agile">
			<div class="container">
				<h3><a href="index.html">Gallery</a></h3>
			</div>
		</div>
<!--Projects-->
<div class="content">
	<div class="projects-agile">
		<div class="container">
					<h2 class="tittle">Gallery</h2>
					
					{% for galleri in gallery %}
							
						<div class="portfolio_grid_w3lss">
							<div class="col-md-4 w3agile_Projects_grid">
								<div class="w3agile_Projects_image">
									<a class="sb" href="{{galleri.image.url}}">
										<figure>
											<img src="{{galleri.image.url}}" alt="" class="img-responsive img-thumbnail" />
											<figcaption>
											<h4>{{galleri.title}}</h4>
											</figcaption>
										</figure>
									</a>
								</div>
							</div>
						</div>
					{% endfor %}
						
						<div class="clearfix"> </div>
					<script type="text/javascript" src="js/smoothbox.jquery2.js"></script>
		</div>
	</div>
</div>



{% endblock content %}

templates/bfsapp/clienttemplates/clientnotecalendar.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}

{% block content %}




{% endblock content %}

templates/bfsapp/clienttemplates/clientruppesh.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block contact %}active{% endblock contact %}


{% block content %}

<div class="new-w3agile">
	<div class="container">
       <h3 class="tittle1">INFORMATION</h3>
				<div class="new-bottom">
					<div class="new-bottom-left">
							<img src="{% static 'clientstatic/images/r1.jpg' %}" style="max-width: 700px; max-height: 330px"  class="img-responsive zoom-img">
								</div>
									<div class="new-bottom-right">
									<h2>Er. Ruppesh Adhikari</h2><br>
									<h3>Qualification:Bachelor in Electronics & Communication Engineering</h3><br>
									<h3>College: Cosmos College of Management and Technology</h3><br>
									<h3>Skills: Python Programming, Django Programming, HTML, Web designing, Electronics project making</h3><br>
									<h3>Address: Malangwa-10, Sarlahi, Nepal</h3><br>
									<h3>Contact: (+977) 9817807980</h3>
									<h3>Email: eruppesh@gmail.com</h3>
									<h3>Contact link: <a href="http://ruppesh.herokuapp.com/">http://ruppesh.herokuapp.com/</a></h3>
									<h3>Contact: (+977) 9817807980</h3>
									<h3>Email: eruppesh@gmail.com</h3>
									<h3>Facebook: <a href="https://www.facebook.com/ruppesh.adhikari.1">ruppesh.adhikari.1</a></h3>
									<h3>Twitter: <a href="https://twitter.com/RuppeshA">twitter.com/RuppeshA</a></h3>
							        </div>
								<div class="clearfix"></div>
					</div>
								<div class="clearfix"></div>
				</div>	
	</div>
</div>





{% endblock content %}

templates/bfsapp/clienttemplates/clientservicelist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block service %}active{% endblock service %}

{% block content %}

<div class="banner-w3agile">
			<div class="container">
				<h3><a>Services</a></h3>
			</div>
		</div>
		<!--content-->
		<div class="content">
			<div class="services-w3l">
				<div class="container">
					<h2 class="tittle">Core Services</h2>
					<div class="services-grids">
						{% for service in services %}
						<div class="col-md-4 ser-grid">
							<div class="icon" style="max-width: 200px; margin: auto;">
								<img src="{{service.image.url}}" class="img-responsive img-circle img-thumbnail">
							</div>
							<h4>{{service.title}}</h4>
							<p>{{service.content}}</p>
						</div>
						{% endfor %}						
						<div class="clearfix"></div>
					</div>
				</div>
			</div>

			
			<div class="our-services-w3">
				<div class="container">
					<h3 class="tittle">Our Features</h3>
					<div class="ourser-grids">
						{% for feature in features %}
						<div class="col-md-4 ourser-grid">
							<div class="mask">
								<img src="{{feature.image.url}}" class="img-responsive zoom-img" />
							</div>
							<h4>{{feature.title}}</h4>
							<p>{{feature.content}}</p>
						</div>
                        {% endfor %}
						<div class="clearfix"></div>

					</div>
				</div>
			</div>
		</div>


{% endblock content %}

templates/bfsapp/clienttemplates/clientthankua.html
<!DOCTYPE html>
<html>
<head>
	<title>thanku</title>
</head>
<body style="background-color: lightgreen"><br><br><br><br><br><br>
<div class="container">
	<h1><center>Your Online Admission form has been<br> Successfully submitted</center></h1>
	<center><a href="{% url 'bfsapp:clienthome' %}"><button><h3>HOME</h3></button></a></center>
	<h1><center>We will Contact You SOON<br> Thanku !</center></h1>

</div>
</body>
</html>

templates/bfsapp/clienttemplates/clientvacancylist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}

{% block content %}
<div class="register-form-main">
		<div class="container">
			<p align="left">
			<div class="title-div"><br>
				{% for vacancy in vacancie %}
				<h1 style="color: green">{{vacancy.title}}</h1>
				<h2>{{vacancy.content}}</h2>
				{% endfor %}
				<h3 style="color: green" class="tittle"><br>
					<span>V</span>acancy
					<span>F</span>orm<hr>
				</h3>
			</div>
			<div class="register-form">
				<form action="{% url 'bfsapp:clientvacancylist' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{form.as_p}}
						<div class="clearfix"> </div><br>
					<input class="btn btn-primary btn-block" type="submit" value="Submit"><hr>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

templates/bfsapp/clienttemplates/resultlist.html
<!DOCTYPE html>
<html>
<head>
	<title>jjyt</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>